version: "3.8"

services:
  sd-webui:
    build: .
    container_name: sd-webui
    ports:
      - "7860:7860"
    volumes:
      - ./models:/app/models
      - ./extensions:/app/extensions
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

